# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Публичный адрес')),
                ('content', models.JSONField(default=dict, verbose_name='Опубликованное содержимое')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Доступна')),
                ('auto_update', models.BooleanField(default=False, verbose_name='Обновлять автоматически')),
                ('views_count', models.PositiveBigIntegerField(default=0, verbose_name='Просмотров')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'db_table': 'published_documents',
            },
        ),
    ]
