# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('attachment', 'Вложение'), ('export', 'Выгрузка'), ('import', 'Загруженный файл'), ('avatar', 'Фотография профиля')], db_index=True, max_length=12, verbose_name='Тип')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер, байт')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалить после')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'stored_files',
                'ordering': ('-created_at',),
            },
        ),
    ]
