# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddIndex(
            model_name='storedfile',
            index=models.Index(fields=['document', 'kind'], name='stored_file_documen_17ff40_idx'),
        ),
    ]
