# Generated by Django 5.1.5 on 2026-09-10 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('document_shared', 'Открыт доступ к документу'), ('comment_added', 'Новый комментарий'), ('comment_reply', 'Ответ на комментарий'), ('mentioned', 'Упоминание'), ('task_assigned', 'Назначена задача'), ('suggestion_added', 'Предложена правка'), ('suggestion_resolved', 'Предложение рассмотрено')], max_length=25, verbose_name='Тип')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='Текст')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
