# Generated by Django 5.1.5 on 2026-09-10 10:20

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтверждён')),
                ('language', models.CharField(default='ru', max_length=5, verbose_name='Язык интерфейса')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('system', 'Как в системе')], default='system', max_length=10, verbose_name='Тема')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Письма о событиях')),
                ('editor_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки редактора')),
                ('cursor_color', models.CharField(blank=True, max_length=7, verbose_name='Цвет курсора')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('purpose', models.CharField(choices=[('confirm_email', 'Подтверждение email'), ('reset_password', 'Сброс пароля')], max_length=20, verbose_name='Назначение')),
                ('token_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хеш кода')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
                'verbose_name_plural': 'Коды подтверждения',
                'db_table': 'user_confirmations',
                'indexes': [models.Index(fields=['purpose', 'expires_at'], name='user_confir_purpose_42e741_idx')],
            },
        ),
    ]
