# Generated by Django 5.1.5 on 2026-09-14 08:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Ключ сопоставления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'db_table': 'route_places',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Часов в пути')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_in', to='routes.place', verbose_name='Куда')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs_out', to='routes.place', verbose_name='Откуда')),
            ],
            options={
                'verbose_name': 'Плечо маршрута',
                'verbose_name_plural': 'Плечи маршрута',
                'db_table': 'route_legs',
                'ordering': ('origin__name', 'destination__name'),
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination'), name='uniq_route_leg'), models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='route_leg_not_self')],
            },
        ),
    ]
