# Generated by Django 5.1.5 on 2026-09-22 10:16

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_initial_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitAmount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, unique=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма, $')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Пояснение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Сумма транзита',
                'verbose_name_plural': 'Суммы транзита',
                'db_table': 'route_transit_amounts',
                'ordering': ('order', 'amount'),
            },
        ),
    ]
