# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('ydoc_state', models.BinaryField(blank=True, null=True, verbose_name='Состояние Yjs')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Название версии')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Документ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменений')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'db_table': 'document_versions',
                'ordering': ('-version_number',),
                'indexes': [models.Index(fields=['document', '-created_at'], name='document_ve_documen_14d337_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_version_number_per_document')],
            },
        ),
    ]
