# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('commenter', 'Комментатор'), ('viewer', 'Читатель')], default='viewer', max_length=10, verbose_name='Роль')),
                ('access', models.CharField(choices=[('restricted', 'Только приглашённые'), ('anyone', 'Все, у кого есть ссылка')], default='restricted', max_length=12, verbose_name='Кому доступно')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Ссылка доступа',
                'verbose_name_plural': 'Ссылки доступа',
                'db_table': 'document_share_links',
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('editor', 'Редактор'), ('commenter', 'Комментатор'), ('viewer', 'Читатель')], default='viewer', max_length=10, verbose_name='Роль')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Доступ к документу',
                'verbose_name_plural': 'Доступы к документам',
                'db_table': 'document_permissions',
            },
        ),
    ]
