# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='documentsharelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='documentsharelink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['user', 'document'], name='document_pe_user_id_c60610_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='uniq_permission_per_user'),
        ),
    ]
