# Generated by Django 5.1.5 on 2026-09-10 10:20

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Без названия', max_length=255, verbose_name='Название')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое')),
                ('ydoc_state', models.BinaryField(blank=True, null=True, verbose_name='Состояние Yjs')),
                ('plain_text', models.TextField(blank=True, editable=False, verbose_name='Текст для поиска')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Поисковый вектор')),
                ('document_mode', models.CharField(choices=[('pages', 'Страницы'), ('pageless', 'Без разбивки на страницы')], default='pages', max_length=10, verbose_name='Режим')),
                ('page_size', models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal')], default='a4', max_length=10, verbose_name='Формат')),
                ('orientation', models.CharField(choices=[('portrait', 'Книжная'), ('landscape', 'Альбомная')], default='portrait', max_length=10, verbose_name='Ориентация')),
                ('margin_top', models.FloatField(default=20, verbose_name='Поле сверху, мм')),
                ('margin_bottom', models.FloatField(default=20, verbose_name='Поле снизу, мм')),
                ('margin_left', models.FloatField(default=25, verbose_name='Поле слева, мм')),
                ('margin_right', models.FloatField(default=15, verbose_name='Поле справа, мм')),
                ('page_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет страницы')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Опубликован')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('allow_download', models.BooleanField(default=True, verbose_name='Разрешить скачивание')),
                ('allow_copy', models.BooleanField(default=True, verbose_name='Разрешить копирование')),
                ('allow_print', models.BooleanField(default=True, verbose_name='Разрешить печать')),
                ('last_edited_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
                'ordering': ('-last_edited_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('opened', 'Открыт'), ('edited', 'Изменён'), ('shared', 'Доступ изменён'), ('commented', 'Прокомментирован'), ('renamed', 'Переименован'), ('moved', 'Перемещён'), ('deleted', 'Удалён'), ('restored', 'Восстановлен'), ('published', 'Опубликован'), ('downloaded', 'Скачан'), ('printed', 'Отправлен на печать'), ('imported', 'Импортирован'), ('copied', 'Скопирован')], db_index=True, max_length=20, verbose_name='Действие')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'Действие с документом',
                'verbose_name_plural': 'Действия с документами',
                'db_table': 'document_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('payload', models.BinaryField(verbose_name='Приращение')),
            ],
            options={
                'verbose_name': 'Приращение документа',
                'verbose_name_plural': 'Приращения документов',
                'db_table': 'document_updates',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалена')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'db_table': 'folders',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StarredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Избранный документ',
                'verbose_name_plural': 'Избранные документы',
                'db_table': 'documents_starred',
            },
        ),
    ]
