# Generated by Django 5.1.5 on 2026-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('text', 'Текстовый документ'), ('sheet', 'Электронная таблица')], db_index=True, default='text', max_length=10, verbose_name='Тип'),
        ),
    ]
