# Generated by Django 5.1.5 on 2026-09-10 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=5000, verbose_name='Текст')),
                ('selection_data', models.JSONField(blank=True, default=dict, verbose_name='Выделение')),
                ('quoted_text', models.TextField(blank=True, verbose_name='Процитированный текст')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Закрыт')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда закрыт')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Задача выполнена')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('emoji', models.CharField(max_length=8, verbose_name='Эмодзи')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'db_table': 'comment_reactions',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('insert', 'Вставка'), ('delete', 'Удаление'), ('replace', 'Замена'), ('format', 'Форматирование')], max_length=10, verbose_name='Операция')),
                ('position', models.JSONField(default=dict, verbose_name='Позиция в документе')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Содержимое правки')),
                ('original_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('suggested_text', models.TextField(blank=True, verbose_name='Предложенный текст')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда решено')),
            ],
            options={
                'verbose_name': 'Предложение правки',
                'verbose_name_plural': 'Предложения правок',
                'db_table': 'suggestions',
                'ordering': ('created_at',),
            },
        ),
    ]
