# Generated by Django 5.1.5 on 2026-09-10 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('category', models.CharField(choices=[('blank', 'Пустой документ'), ('resume', 'Резюме'), ('letter', 'Письмо'), ('report', 'Отчёт'), ('project', 'Проект'), ('study', 'Учебная работа'), ('notes', 'Заметки'), ('business', 'Деловой документ')], db_index=True, default='blank', max_length=20, verbose_name='Категория')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/', verbose_name='Обложка')),
                ('is_building_block', models.BooleanField(db_index=True, default=False, verbose_name='Готовый блок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Показывать')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'document_templates',
                'ordering': ('order', 'title'),
            },
        ),
    ]
