# Generated by Django 5.1.5 on 2026-09-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_templates', '0005_china_trips_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='is_personal',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Личный'),
        ),
    ]
