import { chromium } from 'playwright'
const BASE='http://localhost:8080'
const b = await chromium.launch(); const page = await b.newPage({ viewport:{width:1400,height:900} })
page.on('pageerror', e => console.log('PAGEERROR:', e.message))
await page.goto(`${BASE}/login`)
await page.fill('input[type="email"]','qa@test.local'); await page.fill('input[type="password"]','QaTest12345!')
await page.click('button[type="submit"]'); await page.waitForURL(/\/documents/)
await page.getByRole('button', { name:'Создать таблицу' }).click()
await page.waitForURL(/\/documents\/[0-9a-f-]{36}/); await page.waitForTimeout(2500)

await page.getByLabel('Действия со столбцом D').click()
await page.getByRole('menuitem', { name:/Список значений/ }).click()
await page.waitForTimeout(400)
const dlg = page.getByRole('dialog')
await dlg.locator('textarea').fill(['В пути','Прибыл'].join(String.fromCharCode(10)))
await dlg.getByRole('button', { name:'Сохранить' }).click()
await page.waitForTimeout(500)

await page.locator('[role="grid"]').dblclick({ position:{ x:360, y:44 } })
await page.waitForTimeout(600)
console.log('адрес до выбора:', await page.getByLabel('Выделенный диапазон').innerText())
const list = page.locator('button').filter({ hasText: /^Прибыл$/ })
console.log('кнопок «Прибыл»:', await list.count())
await list.last().click({ force: true })
await page.waitForTimeout(800)
console.log('адрес после:', await page.getByLabel('Выделенный диапазон').innerText())
console.log('строка формул:', await page.getByLabel('Строка формул').inputValue())
const cells = await page.evaluate(() => Array.from(document.querySelectorAll('[role="gridcell"]')).filter(n=>n.textContent.trim()).map(n=>`${n.style.left}/${n.style.top}=${n.textContent.trim()}`))
console.log('ячейки:', JSON.stringify(cells))
await page.screenshot({ path:'qa/shots/probe20.png' })

// Проверяем, дошло ли значение до книги: уходим и возвращаемся.
const url = page.url()
await page.getByLabel('К списку таблиц').click()
await page.waitForURL(/\/documents$/)
await page.waitForTimeout(2000)
await page.goto(url); await page.waitForTimeout(3000)
const after = await page.evaluate(() => Array.from(document.querySelectorAll('[role="gridcell"]')).filter(n=>n.textContent.trim()).map(n=>n.textContent.trim()))
console.log('после перезагрузки:', JSON.stringify(after))
await b.close()
