import { chromium } from 'playwright'
const BASE='http://localhost:8080'
const b = await chromium.launch(); const page = await b.newPage({ viewport:{width:1400,height:900} })
await page.goto(`${BASE}/login`)
await page.fill('input[type="email"]','qa@test.local'); await page.fill('input[type="password"]','QaTest12345!')
await page.click('button[type="submit"]'); await page.waitForURL(/\/documents/)
await page.getByRole('button', { name:'Создать таблицу' }).click()
await page.waitForURL(/\/documents\/[0-9a-f-]{36}/); await page.waitForTimeout(2500)
const type = async (x,y,t) => { await page.locator('[role="grid"]').dblclick({position:{x,y}}); await page.keyboard.type(t); await page.keyboard.press('Enter') }
await type(160,20,'Summa'); await type(160,44,'10'); await type(160,68,'20'); await type(160,92,'30')
const visible = async () => page.evaluate(() => Array.from(document.querySelectorAll('[role="gridcell"]'))
  .filter(n=>n.textContent.trim()).map(n=>n.textContent.trim()))
console.log('до фильтра:', JSON.stringify(await visible()))

await page.getByLabel('Действия со столбцом B').click()
await page.getByRole('menuitem', { name:/^Фильтр/ }).click()
await page.waitForTimeout(600)
const dlg = page.getByRole('dialog')
console.log('окно фильтра:', (await dlg.innerText()).replace(/\n+/g,' | ').slice(0,200))
await dlg.getByRole('button', { name:'Снять все' }).click()
const boxes = dlg.locator('input[type="checkbox"]')
console.log('вариантов:', await boxes.count())
await boxes.nth(1).check()
const checkedLabel = await dlg.locator('label').nth(1).innerText()
console.log('отмечено:', JSON.stringify(checkedLabel))
await dlg.getByRole('button', { name:'Применить' }).click()
await page.waitForTimeout(1000)
console.log('после фильтра:', JSON.stringify(await visible()))
await page.screenshot({ path:'qa/shots/probe15-filter.png' })
await b.close()
