import { chromium } from 'playwright'
const BASE='http://localhost:8080'
const b = await chromium.launch(); const page = await b.newPage({ viewport:{width:1400,height:900} })
await page.goto(`${BASE}/login`)
await page.fill('input[type="email"]','qa@test.local'); await page.fill('input[type="password"]','QaTest12345!')
await page.click('button[type="submit"]'); await page.waitForURL(/\/documents/)
await page.waitForTimeout(1500)
// Создаём документ и копию, как это делает тест.
await page.getByRole('button', { name:'Создать таблицу' }).click()
await page.waitForURL(/\/documents\/[0-9a-f-]{36}/); await page.waitForTimeout(2000)
await page.getByLabel('Название документа').fill('ЦельУдаления'); await page.getByLabel('Название документа').blur()
await page.waitForTimeout(1000)
await page.goto(`${BASE}/documents`); await page.waitForTimeout(1500)

const cards = async () => page.evaluate(() => Array.from(document.querySelectorAll('li'))
  .map(n=>n.textContent.trim().slice(0,40)).filter(t=>t.includes('ЦельУдаления')))
console.log('до удаления:', JSON.stringify(await cards()))
const card = page.locator('li').filter({ hasText: 'ЦельУдаления' }).first()
await card.getByLabel(/Действия/).click()
await page.getByRole('menuitem', { name:'В корзину' }).click()
await page.waitForTimeout(600)
await page.getByRole('dialog').getByRole('button', { name:'Удалить' }).click()
await page.waitForTimeout(1500)
console.log('после удаления:', JSON.stringify(await cards()))
const token = await page.evaluate(() => localStorage.getItem('docs.access'))
const res = await page.request.get(`${BASE}/api/documents/?scope=trash`, { headers:{Authorization:`Bearer ${token}`} })
const body = await res.json()
console.log('в корзине на сервере:', JSON.stringify((body.results||[]).map(d=>d.title)))
await page.screenshot({ path:'qa/shots/probe23-delete.png' })
await b.close()
