import { chromium } from 'playwright'
const BASE='http://localhost:8080'
const b = await chromium.launch(); const page = await b.newPage({ viewport:{width:1400,height:900} })
page.on('console', m => { const t = m.text(); if (t.includes('QA-выбор')) console.log('ИЗ БРАУЗЕРА:', t) })
await page.goto(`${BASE}/login`)
await page.fill('input[type="email"]','qa@test.local'); await page.fill('input[type="password"]','QaTest12345!')
await page.click('button[type="submit"]'); await page.waitForURL(/\/documents/)
await page.getByRole('button', { name:'Создать таблицу' }).click()
await page.waitForURL(/\/documents\/[0-9a-f-]{36}/); await page.waitForTimeout(2500)
await page.getByLabel('Действия со столбцом D').click()
await page.getByRole('menuitem', { name:/Список значений/ }).click()
await page.waitForTimeout(400)
const dlg = page.getByRole('dialog')
await dlg.locator('textarea').fill(['В пути','Прибыл'].join(String.fromCharCode(10)))
await dlg.getByRole('button', { name:'Сохранить' }).click()
await page.waitForTimeout(500)
await page.locator('[role="grid"]').dblclick({ position:{ x:360, y:44 } })
await page.waitForTimeout(600)
const list = page.locator('button').filter({ hasText: /^Прибыл$/ })
await list.last().click()
await page.waitForTimeout(1000)
console.log('строка формул:', JSON.stringify(await page.getByLabel('Строка формул').inputValue()))
console.log('ячейки:', JSON.stringify(await page.evaluate(() => Array.from(document.querySelectorAll('[role="gridcell"]')).filter(n=>n.textContent.trim()).map(n=>n.textContent.trim()))))
await b.close()
